### ISSUE TITLE
How to install using LiveSplitOne

### ISSUE THREAD

**Issue by menmoe** [AlexKnauth/hollowknight-autosplit-wasm#68]
Hey,

I'm having trouble installing the autosplitter. I decided to go for the LiveSplitOne option, as I'm running MacOS. The first thing listed in the README is two links to install, the first one if it's up to date, and if not the second one is there for backup. The first link is out of date, as the latest commit is only as of July 2023. The issue is that the second link doesn't even have anything to download. 
I'm not familiar with rust at all so I might just be missing something very basic idk.

This project is something I find very interesting and I think you guys are doing an amazing thing by letting people on alternative operating systems speedrun properly. I hope you are successful with this and wish you all the best!

**Comment by AlexKnauth** [comment]
I assume you're looking at `livesplit-one-desktop`. You can download that from the command line with:
```sh
git clone https://github.com/AlexKnauth/livesplit-one-desktop.git
```

And after installing Rust, you can compile it with
```sh
cargo build --release
```
From inside the `livesplit-one-desktop` directory. Then, if you're on Mac, I'd recommend running it under `sudo` with
```sh
sudo ./target/release/livesplit-one
```

**Comment by menmoe** [comment]
The first command works
when I try the second command (after moving the directory to the newly-made folder) there are a bunch of very long errors.  But it seems like those errors are just saying that some of the things can't be compiled.
The third command asks for a password (like all sudo commands) and then says "sudo: ./target/release/livesplit-one: command not found"

**Comment by AlexKnauth** [comment]
What's the first error you see when you try the second command?

**Comment by menmoe** [comment]
It starts compiling things and then starts with errors:

error: linking with `cc` failed: exit status: 69
(then there is this: note: env -u IPHONEOS_DEPLOYMENT_TARGET -u TVOS_DEPLOYMENT_TARGET LC_ALL="C" PATH="/Users/main.admin/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Library/Frameworks/Python.framework/Versions/3.11/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/Applications/VMware Fusion Tech Preview.app/Contents/Public:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/main.admin/.cargo/bin" VSLANG="1033" ZERO_AR_DATE="1" "cc" "-arch" "arm64" "/var/folders/x2/d9ch_cld02bg43br48wnjg440000gn/T/rustc9SuOPX/symbols.o" "/Users/main.admin/Desktop/Hollow Knight/speedrunning/livesplit-one-desktop/target/release/build/serde-d5e847e2cd5a27d1/build_script_build-d5e847e2cd5a27d1.build_script_build.467b995df7af9285-cgu.0.rcgu.o" "/Users/main.admin/Desktop/Hollow Knight/speedrunning/livesplit-one-desktop/target/release/build/serde-d5e847e2cd5a27d1/build_script_build-d5e847e2cd5a27d1.q5ff7z16wcysb3q.rcgu.o" "-L" "/Users/main.admin/Desktop/Hollow Knight/speedrunning/livesplit-one-desktop/target/release/deps" "-L" "/Users/main.admin/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib" "/Users/main.admin/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libstd-b7bbc4a3799f91ec.rlib" "/Users/main.admin/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libpanic_unwind-9a832f29e113f2ac.rlib" "/Users/main.admin/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libobject-187acb73fb221979.rlib" "/Users/main.admin/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libmemchr-f379d77720ea5d52.rlib" "/Users/main.admin/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libaddr2line-5f995b6402184362.rlib" "/Users/main.admin/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libgimli-6d4646231255d040.rlib" "/Users/main.admin/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/librustc_demangle-ddf92ea3297b7931.rlib" "/Users/main.admin/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libstd_detect-4bd9fc9ff7289783.rlib" "/Users/main.admin/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libhashbrown-bbf01e0821f9af8a.rlib" "/Users/main.admin/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/librustc_std_workspace_alloc-df3ad4119d36f143.rlib" "/Users/main.admin/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libminiz_oxide-3839cef552c2783c.rlib" "/Users/main.admin/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libadler-130a17e70576817a.rlib" "/Users/main.admin/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libunwind-f7bc4dcd41ebfabc.rlib" "/Users/main.admin/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libcfg_if-3b8c9f0215d4bce7.rlib" "/Users/main.admin/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/liblibc-8e6430dafe1e0d1f.rlib" "/Users/main.admin/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/liballoc-9d92a40a452d227c.rlib" "/Users/main.admin/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/librustc_std_workspace_core-fb23eb00feddf1cb.rlib" "/Users/main.admin/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libcore-c6577f5d4f5dcd9a.rlib" "/Users/main.admin/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libcompiler_builtins-6d556b0e8bf6f23e.rlib" "-lSystem" "-lc" "-lm" "-L" "/Users/main.admin/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib" "-o" "/Users/main.admin/Desktop/Hollow Knight/speedrunning/livesplit-one-desktop/target/release/build/serde-d5e847e2cd5a27d1/build_script_build-d5e847e2cd5a27d1" "-Wl,-dead_strip" "-nodefaultlibs"
  = note: You have not agreed to the Xcode license agreements. Please run 'sudo xcodebuild -license' from within a Terminal window to review and agree to the Xcode and Apple SDKs license.)
there are like 3 of these

**Comment by AlexKnauth** [comment]
> note: You have not agreed to the Xcode license agreements. Please run 'sudo xcodebuild -license' from within a Terminal window to review and agree to the Xcode and Apple SDKs license.

This seems relevant, try doing whatever Xcode stuff it tells you to do.

**Comment by menmoe** [comment]
Wow! the window came up! Thanks so much!

So this is suppose to autosplit?
